server:
  port: 8080
  env: development
  timeout: 60

database:
  clickhouse:
    host: localhost
    port: 9000
    database: healthisis
    username: default
    password: ""
    max_execution_time: 60
    dial_timeout: 10
    conn_max_lifetime: 3600

cors:
  allowed_origins:
    - http://localhost:3000
  allowed_methods:
    - GET
    - POST
    - PUT 
    - DELETE
    - OPTIONS
  allowed_headers:
    - Accept
    - Authorization
    - Content-Type
    - X-CSRF-Token
  exposed_headers:
    - Link
  allow_credentials: true
  max_age: 300
